DROP TABLE IF EXISTS `BOOKS`;

CREATE TABLE BOOKS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ISBN VARCHAR(255) NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	AUTHOR  VARCHAR(255) NOT NULL,
	EDITIONYEAR  VARCHAR(255) NULL,
	PRICE DECIMAL(4,2) NULL
);