DROP TABLE IF EXISTS `books`;

CREATE TABLE books (
	id INT(25) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	isbn VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	author  VARCHAR(255) NOT NULL,
	editionYear  VARCHAR(255) NULL,
	price DECIMAL(6,2) NULL
);